{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.clouding",
    "module": "chatwidget-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "chatwidget-core-1.0.0.jar",
          "url": "chatwidget-core-1.0.0.jar",
          "size": 255290,
          "sha512": "077911b3fe5de362de870e582e39362b4ed3410ba8dba45df1a25a7449438aab5ddf83adeb565f3755c7146e38a2ac48e2a1f05f4d71230af673fccece7012b1",
          "sha256": "940009238e4e01a93ea980ba52ea1ad2a654f845656045ad0485db10890ad227",
          "sha1": "5ce07d4268a868bda265c0b4f89b00c067ef06f0",
          "md5": "bb30bccd812a50ffd16983724a79cc13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "chatwidget-core-1.0.0.jar",
          "url": "chatwidget-core-1.0.0.jar",
          "size": 255290,
          "sha512": "077911b3fe5de362de870e582e39362b4ed3410ba8dba45df1a25a7449438aab5ddf83adeb565f3755c7146e38a2ac48e2a1f05f4d71230af673fccece7012b1",
          "sha256": "940009238e4e01a93ea980ba52ea1ad2a654f845656045ad0485db10890ad227",
          "sha1": "5ce07d4268a868bda265c0b4f89b00c067ef06f0",
          "md5": "bb30bccd812a50ffd16983724a79cc13"
        }
      ]
    }
  ]
}
